### ISSUE TITLE
Changes in Eval.py

### ISSUE THREAD

**Issue by fkavehy** [dhwajraj/deep-siamese-text-similarity#11]
I trained the model and now I need to evaluate it. 
I generated match_valid.tsv file according to the format you proposed. I know I should make small changes in eval.py to add path of my model and graph but I 'm confused and I can't discriminate between model meta file and graph file.
please tell me in which parts should I make changes.
thanks

**Comment by TVect** [comment]
update "checkpoint_dir", "eval_filepath", "vocab_filepath", "model"

batch_predictions, batch_acc, sim = sess.run([predictions,accuracy,sim], {input_x1: x1_dev_b, input_x2: x2_dev_b, input_y:y_dev_b, dropout_keep_prob: 1.0})
--->  batch_predictions, batch_acc, batch_sim = sess.run([predictions,accuracy,sim], {input_x1: x1_dev_b, input_x2: x2_dev_b, input_y:y_dev_b, dropout_keep_prob: 1.0})

**Comment by fkavehy** [comment]
thanks sooooo much TVec.
