### ISSUE TITLE
Accuracy at 56%

### ISSUE THREAD

**Issue by kostaskk** [dhwajraj/deep-siamese-text-similarity#12]
I've gone through the complete training using default values for person_match.train2 and I only get 56% accuracy from the eval script on the autogenerated validation.txt0. Any ideas on what might be the problem? Can others get to the 91% accuracy?

**Comment by dhwajraj** [comment]
problem was only with accuracy printing code. please try with fresh checkout for latest updates compatible with tensorflow v1.2.1
