### ISSUE TITLE
What does "word2vec_model" and "word2vec_format" stand for?

### ISSUE THREAD

**Issue by danner1** [dhwajraj/deep-siamese-text-similarity#29]
tf.flags.DEFINE_string("word2vec_model", "wiki.simple.vec", "word2vec pre-trained embeddings file (default: None)")
tf.flags.DEFINE_string("word2vec_format", "text", "word2vec pre-trained embeddings file format (bin/text/textgz)(default: None)")

**Comment by dhwajraj** [comment]
for sentence level semantic similarity, you may want to initialize word vectors with pre-trained embeddings. word2vec_model is path of that pre-trained model (e.g. googles's billion word word2vec model) 
word2vec_format is format of that model file.
