### ISSUE TITLE
The accuracy is always zero

### ISSUE THREAD

**Issue by whiteablum** [dhwajraj/deep-siamese-text-similarity#3]
Hi,
     When I run the code using the provided training data and default parameters, the distance between two texts changes from 0.7 to 0.6 and the final predictions are all zero. This situation is very strange, it looks like the gradient not works properly. Can you fix it? By the ways, the "n_step" and "n_input" in function "BiRNN" should be equal to "sequence_length" and "embedding_size".

Thx

**Comment by dhwajraj** [comment]
Hi,
In my run with default parameters I do not get accuracies zero or final predictions being all zero. Can you help with more info to reproduce or send me logs.
attached are the logs of my run with all default params:

[run.log.tgz.zip](https://github.com/dhwajraj/deep-siamese-text-similarity/files/671746/run.log.tgz.zip)

**Comment by whiteablum** [comment]
Thx. I got it. I run the code just a few step, so the results look strange. So sorry to bother you.
